config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => :registration
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  


  scope 'api' do
  	resources :menus, only: [:destroy, :create, :update, :index], controller: 'menus_api' do
      resources :menu_items, only: [:destroy, :create, :update, :new], controller: 'menu_items_api'
    end

  end


  root :to => 'site#home'

  get '/manager', to: 'manager#main', as: 'manager_main'
  get '/manager/menu', to: 'manager#menu', as: 'manager_menu'

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord

	has_many :menu_items

	validates :name, presence: true

end

app/models/menu_item.rb
class MenuItem < ApplicationRecord

	belongs_to :menu

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

     validates :username, presence: true    
     validate :role

   def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def after_sign_in_path_for(resource)
  	manager_main_path
  end

  def after_sign_up_path_for(resource)
  	root_path
  end

end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
 	before_action :authenticate_user!
	def main
		render 'main'
	end

	def menu
		
		@theManager = User.find_by_role('manager')
		@menu = Menu.all
		@a_menu = Menu.new
		@items = MenuItem.all
		render 'menu'

	end

end

app/controllers/menu_items_api_controller.rb
class MenuItemsApiController < ApplicationController

	def new
		@the_menu = Menu.find(params[:menu_id])
		@the_item = @the_menu.menu_items.new
	end

	def create
		@menu = Menu.find(params[:menu_id])
		@new_item = @menu.menu_items.new(items_params)

		@new_item.save!
		redirect_to manager_menu_path

	end

	def update
		@menu_item = MenuItem.find(params[:id])
		@menu_item.update(items_params)
		respond_to do |format|
			if @menu_item.save
				format.json {render json: @menu_item}
			else
				format.json { render json: @menu_item.errors, status: :unprocessable_entity }
			end
		end
	end




	def items_params
		params.require(:menu_item).permit(:name, :price, :description)
	end

end

app/controllers/menus_api_controller.rb
class MenusApiController < ApplicationController
	protect_from_forgery with: :null_session
	def index
		theMenu = Menu.all
		render json: theMenu
	end

	def create
		@new_menu = Menu.new(menu_params)


		respond_to do |format| 
			if @new_menu.save
				format.json { render json: @new_menu}
			else
				format.json { render json: @new_menu.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		@menu = Menu.find(params[:id])
		@menu.update(menu_params)
		
		respond_to do |format| 
		if @menu.save
				format.json { render json: @new_menu}
			else
				format.json { render json: @new_menu.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		menu = Menu.find(params[:id])
		menu.destroy
		render json: menu
	end

	def menu_params
		params.require(:menu).permit(:name)
	end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	
	def home
		render 'home'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/menu_items_api_helper.rb
module MenuItemsApiHelper
end

app/helpers/menus_api_helper.rb
module MenusApiHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bombaydarbar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  	<link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Crimson+Text|Playfair+Display|Pinyon+Script" rel="stylesheet">

  </head>

  <body>
  	<% content_for :address do %>
    <div class='address'>
    <a href="https://www.google.com/maps/place/Los+Bandidos+Zaisan/@47.88732,106.913796,17z/data=!3m1!4b1!4m5!3m4!1s0x5d9693c24cdf99ad:0x27134a6a990cf06b!8m2!3d47.88732!4d106.91599" target="_blank" style="text-decoration:none;">Zaisan Street, Zaisan Square, 7th floor, Ulaanbaatar 17023, Mongolia</a>
    <p>9904-4619</p>
  </div>
  <% end %>

  <% if current_page?('/') %>
    <%= yield(:address) %>
    <% end %>
    


    <% if current_user.present? && current_user.role == 'admin'%>
            <nav class='js-sticky-nav'>
      <ul >
        <div class='nav-items to-left'>
        <p>Contact Us</p>
        <%= link_to "Menu", manager_menu_path %>
          </div>
        <div class='nav-items to-center'>
        <p>HOME</p>
        </div>
        <div class='nav-items to-right'>
        <p>Hours</p>
        <p>Us</p>
        <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
        </div>
      </ul> 
    </nav>
      <% else %>

    <nav class="<%= 'js-sticky-nav' if current_page?('/')%>">
      <ul >
        <div class='nav-items to-left'>
        <p>Contact Us</p>
          <p>Menu</p>
          </div>
        <div class='nav-items to-center'>
        <p>HOME</p>
        </div>
        <div class='nav-items to-right'>
        <p>Hours</p>
        <p>Us</p>
        </div>
      </ul> 
    </nav>
        <% end %>        </div>
    <%= yield %>
    <footer>
    <img src="/assets/fb.png" alt='facebook logo'>
      <div class='footer-contents'>
        <p>Contact</p>
        <p class='bullet-point'>&#8226;</p>
        <p>Directions</p>
        <p class='bullet-point'>&#8226;</p>
        <p>Back to top</p>  
      </div>

      <p>&copy; 1999-2017, Los Bandidos</p>
    </footer>
  </body>
</html>

app/views/manager/_edit.html.erb
<p>hello</p>

app/views/manager/menu.html.erb
<div class='container'>
	<div class='a-tab menu-tab menu-titles'>
		<h2>Menu</h2>
		<% current_menu = '' %>
		<% @menu.each do |an_item| %>
			<% current_menu = an_item %>
			<div class='col col-md-6 one-menu'>
			<div class='menu-title'>
			<p class='js-menu-head-<%=an_item.id%> menu-head'><%= an_item.name %></p>
				<div class='menu-head menu-edit-delete'>
					<i class="fa fa-trash-o js-menu-delete" data-menu-id='<%= an_item.id %>' aria-hidden="true"></i>
					<i class="fa fa-pencil-square-o js-menu-edit" data-menu-id='<%= an_item.id %>' aria-hidden="true"></i>
				</div>
			</div>
			<div class='menu-contents'>
			<% @items.each do |item| %>
				<% if item.menu_id == an_item.id %>
				<% item_id = item.id %>
				<div class='single-item-<%= item_id %>'>
				<p class='name-price js-item-name-<%= item_id %>'><%= item.name %>  
					<i class="fa fa-trash-o js-menu-item-delete" data-menu-item-id='<%= item_id %>' data-menu-id='<%= an_item.id %>' aria-hidden="true"></i>  
					<i class="fa fa-pencil-square-o js-menu-item-edit" data-menu-item-id='<%= item_id %>' data-menu-id='<%= an_item.id %>' aria-hidden="true"></i></p>
				<p class='name-price price js-item-price-<%= item_id %>'><%= item.price %></p>
				<p class='description js-item-description-<%= item_id %>'><em><%= item.description %></em></p>
				</div>	
				<% end %>
			<% end %>
				<%= link_to "Create New Item", new_menu_menu_item_path(an_item), :menu_id => an_item.id, class: 'create-new-item' %>
			</div>
			</div>
		<% end %>
			<div class='col col-md-6'>
			<p data-editable class='create-new js-create-new'>
			Create New
			</p>
			</div>
	</div>


</div>

app/views/menu_items_api/new.html.erb
<div class='container'>
	<div class='a-tab'>
	<%= @the_menu.name %>
	<%= form_for [@the_menu, @the_item] do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %><br>
		<%= f.label :price %>
		$<%= f.text_field :price %><br>
		<%= f.label :description %>
		<%= f.text_area :description %> <br>

		<%= f.button %>

	<% end %>
</div>

app/views/site/home.html.erb
<section class='hours-section'>
	<div class='hours'>
		<h2>Hours</h2>
		<div class="time-table">
			<div class="lunch">
				<h3>Lunch</h3>
				<ul>
					<p>Closed</p>
					<p>Closed</p>
					<p>Closed</p>
					<p>12:00PM - 3:00PM</p>
					<p>12:00PM - 3:00PM</p>
					<p>12:00PM - 3:00PM</p>
					<p>12:00PM - 3:00PM</p>
				</ul>
			</div>
			<div class='days'>
				<p>|  Mon  |</p>
				<p>|  Tue  |</p>
				<p>|  Wed  |</p>
				<p>|  Thu  |</p>
				<p>|  Fri  |</p>
				<p>|  Sat  |</p>
				<p>|  Sun  |</p>
			</div>
			<div class='dinner'>
				<h3>Dinner</h3>
				<ul>
					<p>6:00PM - 10:00PM</p>
					<p>Closed</p>
					<p>6:00PM - 10:00PM</p>
					<p>6:00PM - 10:00PM</p>
					<p>6:00PM - 11:00PM</p>
					<p>6:00PM - 11:00PM</p>
					<p>6:00PM - 10:00PM</p>
				</ul>
			</div>
		</div>
	</div>
</section>

<section>
	<div class='about-us'>
		<img class='about-us-image' src='/assets/los.jpg'>
		<div class='about-us-text'>
			<h6>Los Bandidos</h6>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
			<p> * * </p>
		</div>
	</div>
</section>